import { UserRole, type Permission } from "./types.js";

export const rolePermissions: Record<UserRole, Permission[]> = {
  [UserRole.SUPER_ADMIN]: [
    "platform:manage",
    "company:manage",
    "users:manage",
    "subscriptions:manage",
    "security:manage",
    "settings:manage",
    "integrations:manage",
    "workflow:manage",
    "reports:read",
    "sla:monitor",
    "shipments:read",
    "shipments:update",
    "alerts:handle",
    "routes:approve",
    "warehouse:manage",
    "fleet:optimize",
    "risk:analyze",
    "kpi:read",
    "insights:read",
    "deliveries:track",
    "incidents:report",
    "dashboard:read",
  ],
  [UserRole.COMPANY_ADMIN]: [
    "company:manage",
    "users:manage",
    "workflow:manage",
    "integrations:manage",
    "alerts:handle",
    "reports:read",
    "sla:monitor",
    "dashboard:read",
    "shipments:read",
  ],
  [UserRole.OPERATIONS_MANAGER]: [
    "shipments:read",
    "alerts:handle",
    "routes:approve",
    "warehouse:manage",
    "fleet:optimize",
    "dashboard:read",
    "reports:read",
  ],
  [UserRole.ANALYST]: [
    "risk:analyze",
    "reports:read",
    "kpi:read",
    "insights:read",
    "dashboard:read",
    "shipments:read",
  ],
  [UserRole.FIELD_EXECUTIVE]: [
    "shipments:update",
    "shipments:read",
    "deliveries:track",
    "incidents:report",
    "alerts:handle",
  ],
  [UserRole.VIEWER]: ["dashboard:read", "shipments:read", "reports:read"],
};
